on:
  push:
    branches:
      - master



jobs:
  build:
    run-on: ubuntu

    steps:
      - name: 'Testing Githup action'
        run: pwd

      - name: 'Testint Printing'
        run: echo abdo  
        
